<?php

require_once dirname( __FILE__ ) . '/include.php';

class EbpSettings {

  public static function getTablesSQL() {
    //settings  table
    $settingsTable = EbpDatabase::getTableName("settings");

    $settingsSQL = "CREATE TABLE " . $settingsTable ." (
            id INT NOT NULL AUTO_INCREMENT,
            paypalAccount VARCHAR(100) default ' ',
            sandbox VARCHAR(6) default 'false',
            force_ssl_v3 VARCHAR(6) default 'true',
            currency VARCHAR(10) default 'USD',
            couponsEnabled VARCHAR(6) default 'true',
            multipleBookings VARCHAR(6) default 'true',
            SMTP_NAME VARCHAR(100) default 'Name in Email',
            SMTP_EMAIL VARCHAR(255) default 'youremail@host.com',
            SMTP_PASS VARCHAR(255) default 'password',
            SMTP_HOST VARCHAR(255) default 'main.domain.com',
            SMTP_PORT int(10) default '587',
            emailTitle VARCHAR(255) default ' ',
            emailSignature VARCHAR(255) default ' ',
            emailMsg text NOT NULL,
            cpp_header_image VARCHAR(255) default ' ',
            cpp_headerback_color VARCHAR(7) default '#FFFFFF',
            cpp_headerborder_color VARCHAR(7) default '#FFFFFF',
            cpp_logo_image VARCHAR(255) default ' ',
            cpp_payflow_color VARCHAR(7) default '#FFFFFF',
            cal_displayWeekAbbr VARCHAR(5) default 'true',
            cal_displayMonthAbbr VARCHAR(5) default 'false',
            cal_startIn int(1) default '1',
            cal_width int default '600',
            cal_color VARCHAR(7) default '#2ecc71',
            cal_bgColor VARCHAR(7) default '#f6f6f6',
            cal_titleBgColor VARCHAR(7) default '#ffffff',
            cal_dateColor VARCHAR(7) default '#686a6e',
            cal_boxColor VARCHAR(7) default '#ffffff',
            cal_topBorder int default '5',
            cal_topBorderColor VARCHAR(7) default '#2ecc71',
            cal_bottomBorder int default '0',
            cal_bottomBorderColor VARCHAR(7) default '#eeeeee',
            cal_sideBorder int default '0',
            cal_sideBorderColor VARCHAR(7) default ' ',
            cal_paddingSides int default '20',
            passedTxt VARCHAR(100) default 'Event Passed',
            bookingStartsTxts VARCHAR(100) default 'Booking starts on %date% @ %time%',
            bookingEndedTxt VARCHAR(100) default 'Booking ended',
            bookedTxt VARCHAR(100) default 'No spots left',
            btnTxt VARCHAR(100) default 'Book',
            showPrice VARCHAR(5) default 'false',
            showSpots VARCHAR(7) default 'true',
            includeEndsOn VARCHAR(5) default 'true',
            imageMarginSides int default '0',
            imageCrop VARCHAR(5) default 'true',
            imageHeight int default '150',
            imageMarginTop int default '0',
            imageMarginBottom int default '0',
            btnColor VARCHAR(7) default '#FFFFFF',
            btnBgColor VARCHAR(7) default '#2ecc71',
            btnFontSize int default '18',
            btnFontType VARCHAR(6) default 'normal',
            btnLineHeight int default '18',
            btnSidePadding int default '40',
            btnTopPadding int default '12',
            btnBorder int default '0',
            btnBorderColor VARCHAR(7) default '#FFF',
            btnBorderRadius int default '25',
            btnMarginTop int default '10',
            btnMarginBottom int default '20',
            boxWidth int default '400',
            boxPaddingSides int default '0',
            boxPaddingTop int default '0',
            boxPaddingBottom int default '20',
            boxMarginSides int default '0',
            boxMarginBottom int default '20',
            boxAlign VARCHAR(5) default 'true',
            boxMarginTop int default '0',
            boxBgColor VARCHAR(7) default '#FFF',
            boxBorder int default '0',
            boxBorderColor VARCHAR(7) default '#F2F2F2',
            boxBorderRadius int default '5',
            titleColor VARCHAR(7) default '#495468',
            titleFontSize int default '24',
            titleLineHeight int default '36',
            titleTextAlign VARCHAR(6) default 'center',
            titleFontStyle VARCHAR(6) default 'normal',
            titlePaddingSides int default '0',
            titlePaddingTop int default '10',
            titlePaddingBottom int default '10',
            titleMarginTop int default '0',
            titleMarginBottom int default '0',
            titleBottomBorder int default '0',
            titleBottomBorderColor VARCHAR(7) default '#EEEEEE',
            dateTextAlign VARCHAR(6) default 'center',
            datePaddingTop int default '10',
            datePaddingBottom int default '10',
            datePaddingSides int default '0',
            dateMarginTop int default '0',
            dateMarginBottom int default '0',
            dateColor VARCHAR(7) default '#999999',
            dateLableColor VARCHAR(7) default '#666666',
            dateLableSize int default '12',
            dateLabelLineHeight int default '16',
            dateLabelStyle VARCHAR(6) default 'normal',
            dateFontSize int default '14',
            dateFontLineHeight int default '16',
            dateFontStyle VARCHAR(6) default 'normal',
            dateBorderColor VARCHAR(7) default '#EEEEEE',
            dateBorderSize int default '1',
            moreDateTextAlign VARCHAR(6) default 'center',
            moreDateColor VARCHAR(7) default '#c4c4c4',
            moreDateSize int default '12',
            moreDateLineHeight int default '12',
            moreDateMarginTop int default '10',
            moreDateFontStyle VARCHAR(6) default 'normal',
            moreDateHoverColor VARCHAR(7) default '#a3a3a3',
            moreDateOn VARCHAR(5) default 'true',
            moreDatePassed VARCHAR(5) default 'true',
            moreDateUpcoming VARCHAR(5) default 'true',
            moreDateTxt VARCHAR(100) default 'More Dates',
            moreDateSectionMarginBottom VARCHAR(6) default '30',
            modal_dateTitleTextAlign VARCHAR(6) default 'center',
            modal_dateTitlePaddingSides int default '0',
            modal_dateTitleMarginBottom int default '5',
            modal_dateTitleColor VARCHAR(7) default '#000000',
            modal_dateTitleFontSize int default '28',
            modal_dateTitleFontLineHeight int default '30',
            modal_dateTitleFontStyle VARCHAR(6) default 'italic',
            modal_dateTextAlign VARCHAR(6) default 'left',
            modal_datePaddingTop int default '0',
            modal_datePaddingBottom int default '0',
            modal_datePaddingSides int default '20',
            modal_dateMarginTop int default '10',
            modal_dateMarginBottom int default '10',
            modal_dateColor VARCHAR(7) default '#999',
            modal_dateLableColor VARCHAR(7) default '#f2f2f2',
            modal_dateLableSize int default '12',
            modal_dateLabelLineHeight int default '16',
            modal_dateLabelStyle VARCHAR(6) default 'normal',
            modal_dateFontSize int default '14',
            modal_dateFontLineHeight int default '16',
            modal_dateFontStyle VARCHAR(6) default 'normal',
            detailsPaddingTop int default '10',
            detailsPaddingBottom int default '10',
            detailsPaddingSides int default '20',
            detailsMarginTop int default '10',
            detailsMarginBottom int default '0',
            detailsColor VARCHAR(7) default '#999',
            detailsLableColor VARCHAR(7) default '#CCC',
            detailsLableSize int default '14',
            detailsLabelLineHeight int default '32',
            detailsLabelStyle VARCHAR(6) default 'normal',
            detailsFontSize int default '32',
            detailsFontLineHeight int default '32',
            detailsFontStyle VARCHAR(6) default 'normal',
            detailsBorderColor VARCHAR(7) default '#EEE',
            detailsBorderSize int default '0',
            detailsBorderSide int default '0',
            infoMaxHeight int default '100',
            infoExpandText VARCHAR(50) default 'more',
            locationTextAlign VARCHAR(6) default 'left',
            locationColor VARCHAR(7) default '#a5a5a5',
            locationFontSize int default '12',
            locationLineHeight int default '14',
            locationFontStyle VARCHAR(6) default 'normal',
            infoTextAlign VARCHAR(6) default 'left',
            infoColor VARCHAR(7) default '#a5a5a5',
            infoFontSize int default '12',
            infoLineHeight int default '14',
            infoFontStyle VARCHAR(6) default 'normal',
            infoPaddingSides int default '10',
            infoPaddingTop int default '10',
            infoPaddingBottom int default '10',
            infoMarginTop int default '0',
            infoMarginBottom int default '0',
            infoBorderColor VARCHAR(7) default '#eeeeee',
            infoBorderSize int default '1',
            modalMainColor VARCHAR(7) default '#2ecc71',
            modalNameTxt VARCHAR(100) default 'Full Name',
            modalEmailTxt VARCHAR(100) default 'Email Address',
            modalPhoneTxt VARCHAR(100) default 'Phone Number',
            modalAddressTxt VARCHAR(100) default 'Your Address',
            modal_btnTxtColor VARCHAR(7) default '#FFF',
            modal_btnFontSize int default '16',
            modal_btnLineHeight int default '16',
            modal_btnFontType VARCHAR(6) default 'normal',
            modal_btnTopPadding int default '15',
            modal_btnSidePadding int default '35',
            modal_btnMarginTop int default '30',
            modal_btnBorderRadius int default '6',
            modal_titleSize int default '48',
            modal_titleLineHeight int default '48',
            modal_titleFontType VARCHAR(6) default 'normal',
            modal_titleMarginBottom int default '40',
            modal_input_fontSize int default '16',
            modal_input_lineHeight int default '20',
            modal_input_topPadding int default '12',
            modal_input_space int default '10',
            modalBookText VARCHAR(100) default 'Pay Later',
            paypalBtnTxt VARCHAR(100) default 'Pay Now',
            requirePhone VARCHAR(6) default 'true',
            requireAddress VARCHAR(6) default 'true',
            modal_txtColor VARCHAR(7) default '#FFF',
            dateFormat VARCHAR(20) default 'F jS, Y',
            timeFormat VARCHAR(20) default 'g:i A',
            endsOnTxt VARCHAR(255) default 'Ends On:',
            statsOnTxt VARCHAR(255) default 'Starts On:',
            spotsLeftTxt VARCHAR(255) default 'left',
            modalSpotsLeftTxt VARCHAR(255) default 'Spots left:',
            modalQuantityTxt VARCHAR(255) default 'Quantity',
            modalSingleCostTxt VARCHAR(255) default 'Single Cost',
            modalTotalCostTxt VARCHAR(255) default 'Total Cost',
            eventBookedTxt VARCHAR(255) default 'Event Booked!',
            bookingTxt VARCHAR(255) default 'Booking Event ...',
            ExpandTextTxt VARCHAR(255) default 'Expand',
            closeTextTxt VARCHAR(255) default 'Close',
            termsLink VARCHAR(255) default 'terms',
            mapAddressType VARCHAR(20) default 'address',
            mapAddress VARCHAR(255) default '',
            mapZoom int default '16',
            mapType VARCHAR(15) default 'ROADMAP',
            modal_input_txtColor VARCHAR(7) default '#FFFFFF',
            modal_inputHover_txtColor VARCHAR(7) default '#000000',
            modal_input_bgColor VARCHAR(7) default '#FFFFFF',
            modal_inputHover_bgColorHover VARCHAR(7) default '#FFFFFF',
            modal_input_bgColorAlpha int default '20',
            modal_inputHover_bgColorAlpha int default '60',
            modal_selectHoverColor VARCHAR(7) default '#208F4F',
            modal_selectTxtHoverColor VARCHAR(7) default '#FFFFFF',
            modal_selectLabelAsNoneOption VARCHAR(7) default 'true',
            modal_selectNoneOption VARCHAR(50) default '-- select --',
            currencyBefore VARCHAR(7) default 'true',
            emailSubject VARCHAR(255) default 'Event Booking Information',
            emailSSL VARCHAR(6) default 'false',
            emailTemplate TEXT NOT NULL,
            refundEmailTemplate TEXT NOT NULL,
            refundOwnerEmailTemplate TEXT NOT NULL,
            mapHeight int default '120',
            checkBoxMarginBottom int default '20',
            checkBoxMarginTop int default '20',
            checkBoxTextColor VARCHAR(7) default '#EEE',
            checkBoxColor VARCHAR(7) default '#111',
            cal_height int default '400',
            applyTxt VARCHAR(100) default 'Apply',
            couponTxt VARCHAR(100) default 'Coupon',
            freeTxt VARCHAR(100) default 'Free',
            popupOverlayAlpha int default '100',
            modalOverlayColor VARCHAR(7) default '#2ECC71',
            return_same_page VARCHAR(7) default 'true',
            return_page_url VARCHAR(255) default '',
            infoNoButton VARCHAR(7) default 'true',
            calEventDayColor VARCHAR(7) default '#FFFFFF',
            calEventDayColorHover VARCHAR(7) default '#FFFFFF',
            calTodayColor VARCHAR(7) default '#2eCC71',
            calEventDayDotColorHover VARCHAR(7) default '#2ecc71',
            calEventDayDotColor VARCHAR(7) default '#DDDDDD',
            modal_includeTime VARCHAR(7) default 'false',
            email_mode VARCHAR(7) default '3',
            ticketsOrder int default '1',
            permenantMoreButton VARCHAR(7) default 'false',
            ownerEmailTemplate TEXT NOT NULL,
            addToCalendar VARCHAR(7) default 'false',
            addToCalendarText  VARCHAR(50) default '+GoogleCal',
            addToCalendarTextColor VARCHAR(7) default '#ADADAD',
            addToCalendarTextHoverColor VARCHAR(7) default '#CCC',
            addToCalendarTextFontSize int default '12',
            addToCalendarTextFontStyle VARCHAR(50) default 'italic',
            addToCalendarMarginSide int default '5',
            addToCalendarMarginBottom int default '5',
            addToCalendarAlign VARCHAR(10) default 'left',
            doAfterSuccess VARCHAR(15) default 'popup',
            doAfterSuccessRedirectURL VARCHAR(255) default '',
            doAfterSuccessTitle VARCHAR(255) default 'Success!',
            doAfterSuccessMessage VARCHAR(255) default 'Thank you for reserving a spot. Looking forward to seeing you!',
            priceDecimalCount int default '2',
            priceDecPoint VARCHAR(2) default '.',
            priceThousandsSep VARCHAR(2) default ',',
            eventCardShowImage VARCHAR(7) default 'true',
            eventDescriptionTitle VARCHAR(255) default 'Event Information',
            infoTitleFontSize int default '18',
            infoTitleColor VARCHAR(7) default '#111111',
            cardDescriptionBackColor VARCHAR(7) default '#f1f1f1',
            spotsLeftStrict VARCHAR(7) default 'false',
            limitBookingPerEmail VARCHAR(7) default 'false',
            limitBookingPerEmailCount int default '1',
            bookingLimitText VARCHAR(255) default 'You have %left% tickets left!',
            limitBookingPerTime VARCHAR(7) default 'false',
            limitBookingPerTimeCount int default '1',
            bookingLimitTimeText VARCHAR(255) default 'You can only book %left% time!',
            showAllTickets VARCHAR(7) default 'false',
            NoEventsInList VARCHAR(255) default 'No current events.',
            passedOccurencesText VARCHAR(255) default 'Passed Dates:',
            upcomingOccurencesText VARCHAR(255) default 'Upcoming Dates:',
            eventsListFilterColor VARCHAR(7) default '#1abc9c',
            eventsListFilterTextColor VARCHAR(7) default '#FFFFFF',
            eventsListFilterBorderRadius int default '4',
            eventsListFilterFontSize int default '16',
            eventsListFilterPaddingSides int default '13',
            eventsListFilterPaddingVertical int default '8',
            eventsListFilterLable VARCHAR(100) default 'Show All',
            eventCardShowThumbnail VARCHAR(7) default 'true',
            eventCardExpandThumbnailWidth VARCHAR(4) default '15%',
            eventCardThumbnailWidth VARCHAR(4) default '35%',
            eventCardImageAsBackground VARCHAR(7) default 'false',
            calendarImageAsBackground VARCHAR(7) default 'false',
            sendEmailToAdmin VARCHAR(7) default 'true',
            sendEmailToCustomer VARCHAR(7) default 'true',
            cal_hasBoxShadow VARCHAR(7) default 'false',
            box_hasBoxShadow VARCHAR(7) default 'false',
            email_utf8 VARCHAR(7) default 'false',
            tax_rate DECIMAL(10,2) default '0.0',
            showTaxInBookingForm VARCHAR(7) default 'false',
            duplicateOnQuantityText VARCHAR(255) default 'Person %x% information %name_group%- (%name%)%name_group%',
            emailRulesEnabled VARCHAR(7) default 'false',
            emailRule_afterForCameOnly VARCHAR(7) default 'false',
            emailRule_validStatus VARCHAR(255) default 'paid, not paid, success, successful, completed',
            emailBookingCanceled VARCHAR(7) default 'false',
            emailBookingCanceledTemplate int default '-1',
            coupon_expired_msg VARCHAR(255) default 'Coupon has expired.',
            coupon_not_found_msg VARCHAR(255) default 'Coupon not found.',
            coupon_msg VARCHAR(255) default '%name% - Discount of %amount%',
            cal_weeks VARCHAR(255) default 'Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
            cal_weekabbrs VARCHAR(255) default 'Sun, Mon, Tue, Wed, Thu, Fri, Sat',
            cal_months VARCHAR(255) default 'January, February, March, April, May, June, July, August, September, October, November, December',
            cal_monthabbrs VARCHAR(255) default 'Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sept, Oct, Nov, Dec',
            googleMapsEnabled VARCHAR(7) default 'true',
            googleMapsLoadLib VARCHAR(7) default 'true',
            googleMapsAPIKey VARCHAR(255) default '',
            emailOccurenceDeleted VARCHAR(7) default 'false',
            emailOccurenceCanceledTemplate int default '-1',
            eventBoxIncludeAddress VARCHAR(6) default 'false',
            eventCancelledTxt VARCHAR(255) default 'Booking is closed at this moment',
            emailEventCanceled VARCHAR(7) default 'false',
            emailEventCanceledTemplate int default '-1',
            bookingFormTicketCntShowPrice VARCHAR(7) default 'true',
            mobileSeperatePage VARCHAR(7) default 'false',
            statusesCountedAsCompleted VARCHAR(255) default 'paid, not paid, ok, completed, successful, success',
            giftCard_buyBtn VARCHAR(255) default 'Buy',
            giftCard_offlineBtn VARCHAR(255) default 'Send',
            giftCard_paypalBtn VARCHAR(255) default 'Buy',
            giftCard_formTitle VARCHAR(255) default 'Gift card %amount% - %name%',
            giftCard_toSamePerson VARCHAR(255) default 'Send as a gift',
            giftCard_toEmail VARCHAR(255) default 'Recipient email',
            giftCard_toName VARCHAR(255) default 'Recipient name',
            giftCard_toMessage VARCHAR(255) default 'A message to the receiver ...',
            giftCard_limitReached VARCHAR(255) default 'Limit exceeded !',
            giftCard_successTitle VARCHAR(255) default 'Gift card successfully bought',
            giftCard_successMsg VARCHAR(255) default 'Emails with gift cards and confirmation sent!',
            giftCard_buyingTxt VARCHAR(255) default 'Processing your request ...',
            giftCard_offline VARCHAR(7) default 'true',
            giftCard_paypal VARCHAR(7) default 'true',
            giftCard_gateways VARCHAR(7) default '',
            giftCard_ownerEmailTempalte int default '-1',
            giftCard_buyerEmailTempalte int default '-1',
            giftCard_receiverEmailTempalte int default '-1',
            giftCard_returnPage VARCHAR(255) default '',
            giftCard_finsihedMsg VARCHAR(255) default 'This gift card has already been used.',
            giftCard_leftMsg VARCHAR(255) default 'Discount of %amount%',
            PRIMARY KEY (id)
          );";

    return array($settingsSQL);
  }



  public static function getAdminAppSettings() {
    global $wpdb;
    $result = $wpdb->get_row("SELECT emailEventCanceled, emailRulesEnabled, googleMapsEnabled, emailBookingCanceled FROM " . EbpDatabase::getTableName("settings")." where id='1'");

    return $result;
  }


  public static function getSettings($id) {
    global $wpdb;

    if ($id == 8) {
      $settingId = 3;
    } else if ($id > 2 || $id == 2) {
      $settingId = 1;
    } else {
      $settingId = $id;
    }

    $result = $wpdb->get_row("SELECT * FROM " . EbpDatabase::getTableName("settings")." where id='$settingId'");
    $result->hasDayListCalendar = AddOnManager::usesDayCalAddOn();
    $result->hasEmailRules = AddOnManager::usesEmailRules();

    return $result;

  }

  public static function saveSettings($postVars) {
    global $wpdb;
    $dataArra =  array();
    $id = $postVars['id'];

    foreach($postVars as $key=> $value) {
      if ($key != 'pll_ajax_backend' &&  $key != 'action' && $key != 'id') {
        $dataArra[$key]= $value;
      }
    }

    if ($id == 11) {
      if (AddOnManager::usesEmailRules()) {
        eventBookingProEmailsClass::enableCron($postVars['emailRulesEnabled'] == 'true');
      }
    }

    if ($id < 3) {
      if ($id == 2) {
            $id = 1;
      }
      $wpdb->update(EbpDatabase::getTableName("settings"), $dataArra, array('id'=> $id));
    } else if ($id == 8) {
      $wpdb->update(EbpDatabase::getTableName("settings"), $dataArra, array('id'=> '3'));
    } else {
      $wpdb->update(EbpDatabase::getTableName("settings"), $dataArra, array('id'=> 1 ));
      $wpdb->update(EbpDatabase::getTableName("settings"), $dataArra, array('id'=> 2 ));
      $wpdb->update(EbpDatabase::getTableName("settings"), $dataArra, array('id'=> 3 ));
    }

    return array('error'=>null);
  }

}
